blueprints/stock.py
from flask import Blueprint, render_template 
import requests

stock = Blueprint("stock", __name__, url_prefix="/stocks")

@stock.route("/<string:ticker>")
def view_stock(ticker):
  stock_price = fetch_price(ticker)
  return render_template("stock/stock_quote.html", ticker=ticker, stock_price=stock_price)

def fetch_price(ticker):
  data = requests.get("https://financialmodelingprep.com/api/v3/stock/real-time-price/{}".format(ticker.upper()), params={"apikey": "7ee6a284877bac2cf363374463688fcd"}).json() 
  return data["price"]  

templates/base_layout.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}View Stock Prices{% endblock %} - StockApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-light bg-light justify-content-between">
      <a class="navbar-brand">Stock App</a>
      <ul class="navbar-nav mr-auto">
          <li class="nav-item {% if request.url_rule.endpoint == 'home' %}active{% endif %}">
              <a class="nav-link" href="{{ url_for('index') }}">Home</a>
          </li>
      </ul>
    </nav>
    <div class="container mt-3">
      {% block content %}{% endblock %}  
    </div>
  </body>
</html>

templates/home.html
{% extends "base_layout.html" %}
{% block title %} Your Portfolio {% endblock %}

{% block content %}
<div class="row">
  <div class="col-sm">
      <h1>Welcome to StockApp</h1>
      <div> This is a quick way to view the price of stocks </div>
  </div>
  <div class="col-sm">
      {% include 'portfolio.html' %}
  </div>
</div>
{% endblock %}

templates/macros.html
{% macro stock_quote_link(stock_ticker) %}
    <a href="{{ url_for('stock.view_stock', ticker=stock_ticker) }}">{{ stock_ticker }}</a>
{% endmacro %}

templates/portfolio.html
{% from "macros.html" import stock_quote_link %}

<h1>
  View your portfolio
</h1>
<ul>
  {% for ticker in ["FB", "AMZN", "AAPL", "GOOG"] %}
    <li>
      {{stock_quote_link(ticker)}}       
    </li>
  {% endfor %}
</ul>

templates/stock/stock_quote.html
{% extends "base_layout.html" %}
{% block title %} {{ticker}} {% endblock %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm">
      <h1 class="mb-3"> {{ ticker }} </h1>
      <hr />
      <h2> Price: ${{ stock_price }} </h2>
    </div>
    <div class="col-sm">
        {% include "portfolio.html" %}
    </div>
  </div>
</div>
{% endblock %}